replicaCount: 2

image:
  repository: ghcr.io/pramodtidke/tricentis-web-shop/shopwave-discount-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 80
  containerPort: 3013

probes:
  enabled: true
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

env:
  - name: NODE_ENV
    value: production
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: discount-service-secrets
        key: db-host
  - name: DB_PORT
    valueFrom:
      secretKeyRef:
        name: discount-service-secrets
        key: db-port
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: discount-service-secrets
        key: db-name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: discount-service-secrets
        key: db-user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: discount-service-secrets
        key: db-password

