replicaCount: 1
image:
  repository: ghcr.io/pramodtidke/tricentis-web-shop/shopwave-notification-service
  tag: latest
service:
  port: 80
  containerPort: 3010
probes:
  enabled: true
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi
env:
  - name: NODE_ENV
    value: "production"
  - name: RABBITMQ_URL
    valueFrom:
      secretKeyRef:
        name: notification-service-secrets
        key: rabbitmq-url
  - name: MONGO_URI
    valueFrom:
      secretKeyRef:
        name: notification-service-secrets
        key: mongo-uri
