replicaCount: 1

image:
  repository: ghcr.io/pramodtidke/tricentis-web-shop/shopwave-file-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 80
  containerPort: 3016

probes:
  enabled: true
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi

env:
  - name: NODE_ENV
    value: production

