replicaCount: 1

image:
  repository: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/shopwave/auth-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

probes:
  initialDelaySeconds: 15
  path: /health

env:
  - name: PORT
    value: "3001"
  - name: REDIS_URL
    valueFrom:
      secretKeyRef:
        name: auth-service-secrets
        key: redis-url
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: auth-service-secrets
        key: jwt-secret