name: Helm Chart Validation

on:
  pull_request:
    paths:
      - 'helm/**'
  push:
    branches:
      - main
    paths:
      - 'helm/**'

jobs:
  helm-lint-and-template:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: helm/shopwave-microservice

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v4.2.4'

      - name: helm lint
        run: helm lint .

      - name: helm template - api-gateway values
        run: helm template shopwave-api-gateway . -f values.yaml

      - name: helm template - user-service values
        run: helm template shopwave-user-service . -f values-user-service.yaml